# Generated by Django 2.0.2 on 2018-07-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restauran_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restauran',
            new_name='RestaurantsLocation',
        ),
    ]
