# Generated by Django 2.0.2 on 2018-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantslocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocation',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
