# Generated by Django 2.0.2 on 2018-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantslocation_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
