# Generated by Django 2.0.2 on 2018-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantslocation_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
